### ISSUE TITLE
Does this repo address data from NCEM microscope? Specs?

### ISSUE THREAD

**Issue by dani-lbnl** [Xi-CAM/Xi-cam.NCEM#3]

**Comment by ercius** [comment]
It provides an interface to read and display most image data files from TEMs in multiple formats in Xicam. Most image data from NCEM will be readable in Xicam using this plugin. The file readers are provided through [OpcenNCEM](https://github.com/ercius/openNCEM) and [ncempy](https://pypi.org/project/ncempy/).
